<?php

namespace App\Consts;

class AutoCompleteConst
{
    const OS = [
        "AIX",
        "Android",
        "Arch Linux",
        "CentOS",
        "Chrome OS",
        "Debian",
        "FreeBSD",
        "FreeRTOS",
        "Haiku",
        "HarmonyOS",
        "HP-UX",
        "iOS",
        "KaiOS",
        "macOS Big Sur",
        "macOS Catalina",
        "macOS Monterey",
        "NetBSD",
        "OpenBSD",
        "Plan 9",
        "ReactOS",
        "RTLinux",
        "Solaris",
        "Ubuntu",
        "VxWorks",
        "Windows 10",
        "Windows 11",
        "Windows 7",
        "Windows 8",
        "μC/OS"
    ];
    const DATABASE = [
        "Amazon DynamoDB",
        "Amazon Neptune",
        "Apache Cassandra",
        "Apache Hadoop",
        "CouchDB",
        "db4o",
        "Google Bigtable",
        "InfluxDB",
        "MariaDB",
        "Memcached",
        "Microsoft SQL Server",
        "MongoDB",
        "MySQL",
        "Neo4j",
        "ObjectDB",
        "PostgreSQL",
        "Prometheus",
        "Redis",
        "XML DB"
    ];
    const FRAMEWORK = [
        "Angular",
        "Aurelia",
        "Backbone.js",
        "Blazor",
        "Bootstrap",
        "CakePHP",
        "Catalyst",
        "CherryPy",
        "CodeIgniter",
        "D3.js",
        "Django",
        "Django REST framework",
        "Durandal",
        "Electron",
        "Ember.js",
        "Express.js",
        "FastAPI",
        "Feathers",
        "Flask",
        "Flask-RESTful",
        "Flutter",
        "Gatsby",
        "Grails",
        "Hapi.js",
        "Happi",
        "Hibernate",
        "Ionic",
        "Inferno",
        "JHipster",
        "jQuery",
        "Jooby",
        "Keras",
        "KeystoneJS",
        "Koa",
        "Laravel",
        "Lift",
        "Lumen",
        "LoopBack",
        "Meteor",
        "Mojo",
        "NestJS",
        "Next.js",
        "Nuxt.js",
        "Odoo",
        "OpenUI5",
        "Phoenix",
        "Play Framework",
        "Polymer",
        "Quasar",
        "Quarkus",
        "Rails API",
        "React",
        "Redux",
        "Redux Saga",
        "Sails.js",
        "Sapper",
        "Spring",
        "Struts",
        "Symfony",
        "Tide",
        "TurboGears",
        "Umbrella",
        "UmiJS",
        "Unity",
        "Vapor",
        "Vue.js",
        "Wagtail",
        "Web2py",
        "Xamarin",
        "Xamarin.Forms",
        "XState",
        "Yew",
        "Yii",
        "YUI",
        "ZK Framework",
        "Zope"
    ];
    const LANGUAGE = [
        "ABAP",
        "Ada",
        "ActionScript",
        "Alice",
        "AliceML",
        "ALGOL",
        "AngelScript",
        "Apex (Salesforce)",
        "Assembly言語",
        "ATS",
        "Babbage",
        "Ballerina",
        "C",
        "C#",
        "C++",
        "Chapel",
        "Ceylon",
        "Clojure",
        "COBOL",
        "COBOL-IT",
        "COOL",
        "COQ",
        "CSS",
        "Cython",
        "D",
        "Dart",
        "Delphi",
        "Datalog",
        "Dylan",
        "Elixir",
        "Euphoria",
        "Erlang",
        "F#",
        "Factor",
        "Fant0m",
        "Fortran",
        "Forth",
        "Go",
        "Groovy",
        "Haskell",
        "HTML",
        "Io",
        "J",
        "JScript",
        "Java",
        "Janus",
        "JavaScript",
        "Julia",
        "K",
        "Kotlin",
        "LabVIEW",
        "Lisp",
        "Lua",
        "MATLAB",
        "MAXScript",
        "MUMPS",
        "Objective Caml",
        "Objective-C",
        "Oz",
        "Pascal",
        "Perl",
        "PHP",
        "PicoLisp",
        "Pike",
        "PL/SQL",
        "Pop11",
        "PostScript",
        "PowerShell",
        "Prolog",
        "Python",
        "R",
        "Red",
        "Ring",
        "Ruby",
        "Rust",
        "Scala",
        "Scheme",
        "Scilab",
        "Scratch",
        "Shell Script",
        "Shen",
        "Simula",
        "Smalltalk",
        "Swift",
        "SQL",
        "Tcl",
        "TypeScript",
        "VHDL",
        "Verilog",
        "Visual Basic",
        "XSLT",
        "Zsh"
    ];
    const SERVER = [
        "Adobe Media Server",
        "Amazon CloudFront",
        "Amazon EC2",
        "Bind",
        "Apache",
        "Cloudflare",
        "Cisco ASA",
        "FileZilla Server",
        "Fortinet FortiGate",
        "Google Cloud Compute Engine",
        "KVM",
        "Microsoft DNS",
        "Microsoft Exchange Server",
        "Microsoft Hyper-V",
        "Microsoft IIS",
        "Microsoft Azure VM",
        "Microsoft Stream",
        "Nginx",
        "NTP (Network Time Protocol)サーバー",
        "pfSense",
        "Postfix",
        "ProFTPD",
        "Pure-FTPd",
        "Samba",
        "Sendmail",
        "Tomcat",
        "Unbound",
        "VMware vSphere/ESXi",
        "vsftpd",
        "WebSphere",
        "WildFly",
        "Wowza Streaming Engine"
    ];
    const MIDDLWARE = [
        "ASP.NET Core Authentication",
        "ASP.NET Core Middleware",
        "ASP.NET Middleware",
        "ASP.NET Web API Middleware",
        "Connect Morgan",
        "Django GraphQL",
        "Django Logging",
        "Django Middleware",
        "Express GraphQL",
        "Express Morgan",
        "Express Proxy Middleware",
        "Express.js Middleware",
        "Express.js Passport",
        "Flask",
        "Flask Middleware",
        "Koa",
        "Laravel Middleware",
        "NGINX",
        "Node.js Middleware",
        "Ruby on Rails Middleware",
        "Spring Security"
    ];
    const VERSION_MANAGEMENT = [
        "AccuRev",
        "AllChange",
        "Alienbrain",
        "ArX",
        "Assembla",
        "AWS CodeCommit",
        "Beanstalk",
        "Bitbucket",
        "Bazaar",
        "ClearCase",
        "CodePlex",
        "Concurrent Versions System (CVSNT)",
        "Continuus",
        "CVS",
        "Darcs",
        "Flashline",
        "Fossil",
        "Git",
        "GitHub",
        "GitLab",
        "Gitea",
        "GNU Arch",
        "IBM Configuration Management Version Control (CMVC)",
        "Kallithea",
        "Mercurial",
        "MercurialEclipse",
        "Monotone",
        "MKS Source Integrity",
        "Perforce",
        "Plastic SCM",
        "PVCS",
        "Rational Team Concert (RTC)",
        "RCS",
        "RhodeCode",
        "SCCS",
        "SCM Manager",
        "SourceForge",
        "SourceGear Vault",
        "StarTeam",
        "SubGit",
        "Subversion",
        "Surround SCM",
        "Team Foundation Version Control (TFVC)",
        "Vesta",
        "VersionOne",
        "VersionRecall",
        "Visual SourceSafe (VSS)",
        "Veracity"
    ];
    const VIRTUAL_ENVIRONMENT = [
        "AWS EC2 (Amazon Elastic Compute Cloud)",
        "Docker",
        "Google Cloud Compute Engine",
        "HashiCorp Nomad",
        "Hyper-V",
        "KVM (Kernel-based Virtual Machine)",
        "LXC (Linux Containers)",
        "LXD (Linux Container Daemon)",
        "Microsoft Azure Virtual Machines",
        "Minikube",
        "OpenVZ",
        "Oracle VM VirtualBox",
        "Parallels",
        "Proxmox Virtual Environment",
        "QEMU",
        "Rancher",
        "Vagrant",
        "VirtualBox",
        "VMware",
        "Xen"
    ];
}
